// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0OIW0-BbUboeX374PN324LV7jIrKy8QI',
    appId: '1:284283271659:web:4d7dc38e52b62a906a81ae',
    messagingSenderId: '284283271659',
    projectId: 'to-do-app-5a968',
    authDomain: 'to-do-app-5a968.firebaseapp.com',
    storageBucket: 'to-do-app-5a968.appspot.com',
    measurementId: 'G-FHB1KTL4V1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYpEyVWGbI42OMK4IOcpUKmWPAPW9ONK4',
    appId: '1:284283271659:android:8fce31716e3ae62d6a81ae',
    messagingSenderId: '284283271659',
    projectId: 'to-do-app-5a968',
    storageBucket: 'to-do-app-5a968.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqpEBi-zm8baRCCXegLELD58Yfk6_8BlI',
    appId: '1:284283271659:ios:9c211d284f8678f76a81ae',
    messagingSenderId: '284283271659',
    projectId: 'to-do-app-5a968',
    storageBucket: 'to-do-app-5a968.appspot.com',
    iosBundleId: 'com.example.toDoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqpEBi-zm8baRCCXegLELD58Yfk6_8BlI',
    appId: '1:284283271659:ios:9c211d284f8678f76a81ae',
    messagingSenderId: '284283271659',
    projectId: 'to-do-app-5a968',
    storageBucket: 'to-do-app-5a968.appspot.com',
    iosBundleId: 'com.example.toDoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0OIW0-BbUboeX374PN324LV7jIrKy8QI',
    appId: '1:284283271659:web:46d0916e178895fe6a81ae',
    messagingSenderId: '284283271659',
    projectId: 'to-do-app-5a968',
    authDomain: 'to-do-app-5a968.firebaseapp.com',
    storageBucket: 'to-do-app-5a968.appspot.com',
    measurementId: 'G-NH8EE9274J',
  );
}
